version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/vuln-js"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/vuln-py"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
